import { TechTool } from "../../types";

export const techTools: TechTool[] = [
  {
    id: 1,
    name: "Google Analytics 4",
    description: "Advanced web analytics and user behavior tracking",
    icon: "/images/logos/google.svg",
    category: "analytics",
    expertise: 95,
    certification: "Google Analytics Certified",
  },
  {
    id: 2,
    name: "Meta Ads Manager",
    description: "Facebook & Instagram advertising platform",
    icon: "/images/logos/facebook.svg",
    category: "advertising",
    expertise: 90,
    certification: "Meta Blueprint Certified",
  },
  {
    id: 3,
    name: "SEMrush",
    description: "Comprehensive SEO and content marketing suite",
    icon: "/images/logos/semrush.svg",
    category: "seo",
    expertise: 88,
    certification: "SEMrush Certified Professional",
  },
  {
    id: 4,
    name: "Mailchimp",
    description: "Email marketing and automation platform",
    icon: "/images/logos/mailchimp.svg",
    category: "marketing",
    expertise: 92,
    certification: "Mailchimp Partner",
  },
  {
    id: 5,
    name: "HubSpot",
    description: "Inbound marketing and CRM platform",
    icon: "/images/logos/hubspot.svg",
    category: "marketing",
    expertise: 85,
    certification: "HubSpot Certified",
  },
  {
    id: 6,
    name: "Adobe Creative Suite",
    description: "Professional design and content creation tools",
    icon: "/images/logos/adobe.svg",
    category: "development",
    expertise: 87,
  },
  {
    id: 7,
    name: "WordPress",
    description: "Website development and CMS platform",
    icon: "/images/logos/wordpress.svg",
    category: "development",
    expertise: 94,
    certification: "WordPress Expert",
  },
  {
    id: 8,
    name: "Hootsuite",
    description: "Social media management and scheduling",
    icon: "/images/logos/hootsuite.svg",
    category: "social",
    expertise: 89,
    certification: "Hootsuite Professional",
  },
];
